version: "3.2"

services:
    webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./www:/var/www/html/
        - ./site.conf:/etc/nginx/conf.d/default.conf